### ISSUE TITLE
Prepare PR for instant core

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/instant-demo#1]
Jembi says open the PR and then they'll help/converse with us about what it should look like... but it will be very nice to get microservice spun up as a package (with some example `project.yaml`) in the standard Instant OpenHIE demo!

Consider which jobs?
Send to HAPI FHIR?
Reconfigure on the fly?

examples:
- https://github.com/jembi/who-covid19-surveillance-package
- https://github.com/openhie/instant/tree/master/mhero ... there should be an `openfn/microservice` directory (some decent namespace?) in the `instant` repo like there's an `mhero` directory here

much of your stuff should be in a folder called `openfn-microservice`

**Comment by taylordowns2000** [comment]
Definitely want this: https://github.com/OpenFn/microservice/issues/24

**Comment by stuartc** [comment]
https://github.com/openhie/instant/pull/101

I can mark this as done right, their feedback will inform the next story @taylordowns2000 ?

**Comment by taylordowns2000** [comment]
Yebo! And in the future, this repo might even die :-)
