### ISSUE TITLE
Set up FHIR Data Pipes

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/instant-demo#8]
### Description
FHIR data pipes implementation and maybe the https://github.com/google/fhir-data-pipes/wiki/Build-a-dashboard-with-FHIR-Data-Pipes-and-Apache-Superset tutorial would be very helpful

![image (1)](https://github.com/OpenFn/instant-demo/assets/6592749/3f21506b-6cc8-4dfd-a382-0bc983ef9f7a)

### Planning
1. you’ve got a hapi fhir server running
2. you’ve got a Spark Thrift server running - see if you can run some queries
3. you could execute a query to that spark thrift server by using OpenFn (maybe creating a new adaptor, but HOPEFULLY using either the http or some SQL-based adaptor)
4. then you could do a transformation in language-common
5. then you could load into the DHIS2 play instance

**Comment by mtuchi** [comment]
FHIR Pipeline controller kept on clashing when i click **Run Full**, i left an issue on https://github.com/google/fhir-data-pipes/issues/782

**Comment by mtuchi** [comment]
![Screenshot 2023-07-31 at 11.12.47 AM.png](https://images.zenhubusercontent.com/6310851c29415866ce13fb98/193dd778-2269-4aeb-be8d-a8fce1b20d54)

**Comment by mtuchi** [comment]
Feedback from google-fhir team https://github.com/google/fhir-data-pipes/issues/782#issuecomment-1666165785

**Comment by taylordowns2000** [comment]
@mtuchi , Fred has offered to help us get this set up and has shared a walkthrough video with you: "OHS FHIR analytics demo.webm"
